package com.beekeeplog.app.domain.model

/** Intent types recognised by the NLP pipeline. */
enum class IntentType {
    UPDATE_STATUS_CELL,
    UPDATE_STATUS_VIRGIN,
    UPDATE_STATUS_LAYING,
    MARK_EMPTY_SWARMED,
    MARK_LOST,
    MARK_SOLD,
    MARK_CULLED,
    MARK_DRONE_LAYER,
    NO_CHANGES,
    MARK_RESERVED,
    MARK_ELITE,
    SET_AGGRESSION,
    ADD_NOTE,
    NEEDS_FEEDING,
    NEEDS_TREATMENT,
    QUERY_COUNT_BY_STATUS,
    QUERY_COUNT_BY_GENETICS,
    QUERY_READY_FOR_SALE,
    QUERY_EMPTY_NUCS,
    QUERY_OVERDUE,
    UNKNOWN
}
